### 注册账号
POST {{ host }}/merchant/api/v1/public/register
Content-Type: application/json

{
  "username": "{{ username }}",
  "password": "{{ password }}",
  "invite_code": "888888"
}


### 密码登录
POST {{ host }}/merchant/api/v1/public/login
Content-Type: application/json

{
  "username": "{{ username }}",
  "password": "{{ password }}"
}

> {%
    client.global.set("token", response.body.data.token);
    client.global.set("username", response.body.data.username);
%}

### 发送验证码
POST {{ host }}/merchant/api/v1/public/sendSms
Content-Type: application/json

{
  "username": "{{ username }}"
}

### 发送邮件
POST {{ host }}/merchant/api/v1/public/sendEmail
Content-Type: application/json

{
  "username": "{{ username }}",
  "email": "szpengjian@gmail.com"
}


### 重置密码
POST {{ host }}/merchant/api/v1/public/repass
Content-Type: application/json

{
  "username": "{{ username }}",
  "password": "{{ password }}",
  "type": "email",
  "code": "795916"
}

### 开通的城市列表
GET {{ host }}/merchant/api/v1/public/tax_list
Content-Type: application/json
Authorization: Bearer {{ token }}


### 公司名称搜索
POST {{ host }}/merchant/api/v1/company/search
Content-Type: application/json
Authorization: Bearer {{ token }}

{
  "keywords": "佛旭文化",
  "type": "1"
}

### 公司详情
POST {{ host }}/merchant/api/v1/company/detail
Content-Type: application/json
Authorization: Bearer {{ token }}

{
  "name": "上海佛旭文化传播有限公司"
}

### 营业执照识别
POST {{ host }}/merchant/api/v1/company/ocr
Content-Type: application/json
Authorization: Bearer {{ token }}

{
  "image": "https://img0.baidu.com/it/u=1046212889,443452567&fm=253&app=120&f=JPEG?w=500&h=749"
}


### 发送短信
POST {{ host }}/merchant/api/v1/tax/sendSms
Content-Type: application/json
Authorization: Bearer {{ token }}

{
  "username": "{{ username }}",
  "password": "Aa123456",
  "client_id": "{{ client_id }}"
}

> {%
    client.global.set("account_uuid", response.body.data.account_uuid);
    client.global.set("public_uuid", response.body.data.public_uuid);
    client.global.set("sms_code_id", response.body.data.sms_code_id);
    client.global.set("signature_key", response.body.data.signature_key);
%}

### 登录账号
POST {{ host }}/merchant/api/v1/tax/login
Content-Type: application/json
Authorization: Bearer {{ token }}

{
  "client_id": "{{ client_id }}",
  "account_uuid": "{{ account_uuid }}",
  "public_uuid": "{{ public_uuid }}",
  "sms_code_id": "{{ sms_code_id }}",
  "signature_key": "{{ signature_key }}",
  "sms_code": "866678"
}

> {%
    client.global.set("access_token", response.body.data.access_token);
%}


### 账号信息
POST {{ host }}/merchant/api/v1/tax/info
Content-Type: application/json
Authorization: Bearer {{ token }}

{
  "client_id": "{{ client_id }}",
  "public_uuid": "{{ public_uuid }}",
  "access_token": "{{ access_token }}",
  "signature_key": "{{ signature_key }}"
}

> {%
    client.global.set("user_id", response.body.data.user_id);
%}


### 默认手机号码
POST {{ host }}/merchant/api/v1/tax/account/DefaultMobile
Content-Type: application/json
Authorization: Bearer {{ token }}

{
  "user_id": "{{ user_id }}",
  "client_id": "{{ client_id }}",
  "public_uuid": "{{ public_uuid }}",
  "access_token": "{{ access_token }}",
  "signature_key": "{{ signature_key }}"
}

> {%
    client.global.set("mobile_id", response.body.data.mobileId);
%}


### 修复手机号码 1发送短信
POST {{ host }}/merchant/api/v1/tax/account/GetSmsCode
Content-Type: application/json
Authorization: Bearer {{ token }}

{
  "user_id": "{{ user_id }}",
  "client_id": "{{ client_id }}",
  "access_token": "{{ access_token }}",
  "signature_key": "{{ signature_key }}",
  "mobile_id": "{{ mobile_id }}"
}



### 修复手机号码 2发送短信
POST {{ host }}/merchant/api/v1/tax/account/VerifyOldSmsCode
Content-Type: application/json
Authorization: Bearer {{ token }}

{

}
### 修复手机号码 3发送短信
POST {{ host }}/merchant/api/v1/tax/account/VerifyOldSmsCode
Content-Type: application/json
Authorization: Bearer {{ token }}

{

}
### 修复手机号码 4发送短信
POST {{ host }}/merchant/api/v1/tax/account/VerifyOldSmsCode
Content-Type: application/json
Authorization: Bearer {{ token }}

{

}